info:
  server:
    name: 注册服务

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
#  server:
#    enableSelfPreservation: false
#    waitTimeInMsWhenSyncEmpty: 0